-- creates the db hbtn_0d_usa
-- creates table cities in the db
-- cities description
--    id INT UNIQUE NOT NULL PRIMARY KEY (autogenerated),
--    name VARCHAR(256) NOT NULL
--    state_id INT NOT NULL FOREIGN KEY (refers to id of the states table)

CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
USE hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS cities(
    id INT UNIQUE NOT NULL AUTO_INCREMENT,
    state_id INT NOT NULL,
    name VARCHAR(256) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (state_id) REFERENCES states(id)
);
